### PR TITLE
Backoff & Retry for Auth0 429 Responses; Throttling

### LINKED ISSUE #47: Auth0 authenticator return 429
The service returns 500s for any request since the auth0 authenticator gets stuck in a "too many requests" state. This needs to be properly handled by the api

```
$ l0 service logs --tail 100 dimsio
dimsio
------
2017/08/01 20:07:44 [ERROR] Authenticator encountered an unexpected error: Invalid status code: 429
2017/08/01 20:07:50 [ERROR] Authenticator encountered an unexpected error: Invalid status code: 429
2017/08/01 20:07:55 [ERROR] Authenticator encountered an unexpected error: Invalid status code: 429
2017/08/01 20:08:14 [ERROR] Authenticator encountered an unexpected error: Invalid status code: 429
2017/08/01 20:08:18 [ERROR] Authenticator encountered an unexpected error: Invalid status code: 429
2017/08/01 20:08:20 [ERROR] Authenticator encountered an unexpected error: Invalid status code: 429
2017/08/01 20:08:24 [ERROR] Authenticator encountered an unexpected error: Invalid status code: 429
```

### PR DESCRIPTION
**Pull request by tlake**
**What does this pull request do?**
If Auth0 returns a 429 response ("too many requests"), the Authenticator will keep retrying after an increasing period of time until the authentication request is able to get through and the credentials are found to be valid or invalid.

**How should this be tested?**
Spin up an API locally (you'll get more output with `export DIMSIO_DEBUG=true`), then hammer it with bad requests.

```
# spins up two backgrounded processes that hammer an api running on localhost:9090

(for x in {0..49}; do echo "Request A-$x:"; curl -u bad0:bad0 localhost:9090/repository/tlake; echo; done) & P1=$! ; (for x in {0..49}; do echo "Request B-$x:"; curl -u bad0:bad1 localhost:9090/repository/tlake; echo; done) & P2=$!; wait $P1 $P2
```

**Checklist**
- [x] Unit tests
- [ ] Smoke tests
- ~System tests~
- ~Documentation~

closes #47

### CODE REVIEW

File: auth/auth0_manager.go [hunk 1]
```diff
@@ -36,16 +41,32 @@ const (
 	validAuthExpiry = 1 * time.Hour
 )
 
-func NewAuth0Manager(domain, clientID, connection string) *Auth0Manager {
+func NewAuth0Manager(domain, clientID, connection string, throttleMin int) *Auth0Manager {
```
Comment (zpatrick) [inline auth/auth0_manager.go]: This seems over-complicated. 

I think the `Auth0Manager` only needs one more field, `throttle <-chan Time`. 
We should take the rateLimit as a `time.Duration` param, and just generate the throttle field using only that rate, e.g:
```
func NewAuth0Manager(domain, clientID, connection string, rateLimit time.Duration) *Auth0Manager {
    return &Auth0Manager{
        ...
        throttle: time.Tick(rateLimit),
    }
}
```

That way in tests, we can just pass in a really high rate limit.

File: auth/auth0_manager.go [hunk 2]
```diff
@@ -36,16 +41,32 @@ const (
...
+		cache:              cache.New(),
+		throttle:           time.Tick(time.Millisecond * time.Duration(throttleMin)),
+		throttleMin:        throttleMin,
+		throttleMultiplier: throttleMin,
+		lastThrottled:      time.Now(),
 	}
 }
 
 func (a *Auth0Manager) Authenticate(username, password string) (bool, error) {
+	if a.throttleMultiplier > a.throttleMin && time.Since(a.lastThrottled) > 1*time.Minute {
```
Comment (zpatrick) [inline auth/auth0_manager.go]: we only need to throttle before we make calls to the auth0 api

File: auth/auth0_manager.go [hunk 3]
```diff
@@ -71,12 +95,25 @@ func (a *Auth0Manager) Authenticate(username, password string) (bool, error) {
 	}
```
Comment (zpatrick) [inline auth/auth0_manager.go]: Again, I think this is over-complicated. For now, we only need to throttle before making the auth0 call:
```
<-a.throttle
if err := a.client.Post("/oauth/ro", req, nil); err != nil { ... }
```
This is the **only** place we should deal with throttling, since it's only the auth0 api giving us the 429 response.

Assuming this is enough to prevent the 429 response, then we don't need all of this extra backoff/retry logic. 
Let's keep it simple for now.

File: auth/auth0_manager.go (hunk 2 above)
Comment (tlake) [inline auth/auth0_manager.go]: Right - this logic is decreasing the backoff.

The increase comes when a 429 is returned from making the authentication, and the throttle is waited for between the token auth and the auth0 auth; that way, requests using a valid token aren't throttled.

This bit of logic I put at the very start because I wanted the checks for decreasing the delay to happen on every request. It avoids a scenario like the following:

```
1. On a Monday, someone generates a swarm of bad auths and ratchets the throttle up to like 32 min, then stops.
2. All throughout the rest of the week, nobody makes a request without a valid token, so the decrease-throttle logic is never run
3. Next week, someone tries to authenticate using Auth0 for the first time in a week, and they still have to sit through 32 (or 16, depending on where this logic sits) min for last week's throttle
```

File: auth/auth0_manager.go [hunk 4]
```diff
@@ -94,35 +96,30 @@ func (a *Auth0Manager) Authenticate(username, password string) (bool, error) {
...
-			if cachedStatus.penalty > maxPenalty {
-				cachedStatus.penalty = maxPenalty
-			}
-
-			if err.Response.StatusCode == 429 {
-				if a.throttleMultiplier > 0 {
-					a.throttleMultiplier = a.throttleMultiplier * 2
-				} else {
-					a.throttleMultiplier = 1
+	for backoff := time.Duration(0); true; backoff += time.Millisecond * 500 {
```
Comment (zpatrick) [inline auth/auth0_manager.go]: For safety, lets add parens around this part `backoff += (time.Millisecond * 500)`

File: auth/auth0_manager.go [hunk 5]
```diff
@@ -94,35 +96,30 @@ func (a *Auth0Manager) Authenticate(username, password string) (bool, error) {
...
-				a.lastThrottled = time.Now()
 			}
 
-			a.cache.Add(key, cachedStatus)
-			return false, nil
+			return false, err
 		}
 
-		return false, err
+		log.Printf("User '%s' sent valid Auth0 credentials.", username)
```
Comment (zpatrick) [inline auth/auth0_manager.go]: Forgot to add `[DEBUG] ` to the start of this log.

File: auth/auth_test.go [hunk 6]
```diff
@@ -7,13 +7,14 @@ import (
...
 	"testing"
+	"time"
 )
 
 type Handler func(w http.ResponseWriter, r *http.Request)
 
 func newAuth0ManagerAndServer(handler Handler) (*Auth0Manager, *httptest.Server) {
 	server := httptest.NewServer(http.HandlerFunc(handler))
-	auth0Manager := NewAuth0Manager(server.URL, "", "", 500)
+	auth0Manager := NewAuth0Manager(server.URL, "", "", 500*time.Millisecond)
```
Comment (zpatrick) [inline auth/auth_test.go]: Better format when specifying some sort of rate is `period/events`, so this would be `time.Second/2`

File: main.go [hunk 7]
```diff
@@ -100,7 +101,7 @@ func main() {
 		auth0Manager := auth.NewAuth0Manager(c.String("auth0-domain"),
 			c.String("auth0-client-id"),
 			c.String("auth0-connection"),
-			500)
+			time.Millisecond*500)
```
Comment (zpatrick) [inline main.go]: ditto - `time.Second/2`

File: auth/auth0_manager.go (hunk 5 above)
Comment (tlake) [inline auth/auth0_manager.go]: Oops ✅

File: auth/auth_test.go (hunk 6 above)
Comment (tlake) [inline auth/auth_test.go]: Gotcha ✅

File: main.go (hunk 7 above)
Comment (tlake) [inline main.go]: ✅

File: auth/auth0_manager.go (hunk 4 above)
Comment (tlake) [inline auth/auth0_manager.go]: ✅
