### PR TITLE
Stress tests

### LINKED ISSUE #24: Add stress tests
We should have tests to verify that d.ims.io can handle many concurrent requests of `docker push/pull` on a wide array of image sizes.

### LINKED ISSUE #37: Swagger Host Config and ELB Cert mismatch
Swagger methods fail to execute after authentication presumably due to `SWAGGER_HOST` configuration in the task definition and/or the cert mismatch on the currently configured ELB.

Current production task definition is configured for:
```
        {
          "name": "DIMSIO_SWAGGER_HOST",
          "value": "l0-production-dimsio5b5999-877291706.us-west-2.elb.amazonaws.com"
        }
```

This config will fail to execute methods via Swagger and `curl`, although `curl` will be successful if passing the `--insecure` param. This behavior has been confirmed by @tlake as well.

### PR DESCRIPTION
**Pull request by zpatrick**
closes #24 
closes #37

### CODE REVIEW

File: test/stress_test.go [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+		"victor",
+		"whiskey",
+		"x-ray",
+		"yankee",
+		"zulu",
+	}
+
+	var i int
+	return func() (string, string, string) {
+		name := nato[i%len(nato)]
```
Comment (tlake) [inline test/stress_test.go]: Slick loop in this generator.
