### PR TITLE
CreateRepository: Return an error if 'name' field contains a slash character

### LINKED ISSUE #43: Cannot retrieve repository whose name contains slashes
# About
Currently, we cannot access a repository whose name contains slashes, like so: `docker.ims.io/repository/tlake/test/with/slashes`

I think it's probably fine for that to be our contract, but if so, there are a couple of things that should be done:

1. Explicitly call out this behavior, at least in the README
2. Throw an error/warning/information message at `POST docker.ims.io/repository/owner ; body={"name":"string"}` if either `owner` or `string` contains a slash character
3. Have a conversion plan for repos on the older d.ims.io (which seems to allow these slashes)

The older d.ims.io seemed to allow this convention, as there are some repos with slashes in their names that have been migrated to docker.ims.io and which cannot currently be accessed from the new docker.ims.io.

If we _do_ want to allow this convention in docker.ims.io, we should fix this behavior as a bug. Whadday'all think?

# Repro

### Create two test repositories:
- POST `docker.ims.io/repository/tlake` body=`{"name":"test-without-slashes"}`
- POST `docker.ims.io/repository/tlake` body=`{"name":"test/with/slashes"}`

Both creation commands complete properly.

### Describe those repositories:
- GET `docker.ims.io/repository/tlake/test-without-slashes`
- GET `docker.ims.io/repository/tlake/test/with/slashes`

The first one succeeds, but the second fails with `404 page not found`.

### PR DESCRIPTION
**Pull request by tlake**
# What does this pull request do?
Fixes a bug where a user could create a repository with a name that contained one or more slashes. This registry frontend does not support lookup of repositories that contain slashes, and allowing a user to create such a repository resulted in a repository that could not be accessed.

# How should this be tested?
Confirm that attempting to create a repository whose name contains a slash character fails with an appropriate error message.

# Checklist
- [x] Unit tests
- ~Smoke tests (if applicable)~
- ~System tests (if applicable)~
- [x] Documentation (if applicable)

# What does this pull request resolve?
Closes #43

### CODE REVIEW

File: controllers/repository_test.go [hunk 1]
```diff
@@ -34,6 +35,20 @@ func TestCreateRepository(t *testing.T) {
...
+func TestCreateRepositoryFailsWithSlashes(t *testing.T) {
+	ctrl := gomock.NewController(t)
+	defer ctrl.Finish()
+
+	mockECR := mock.NewMockECRAPI(ctrl)
+	controller := NewRepositoryController(mockECR)
+
+	c := generateContext(t, models.CreateRepositoryRequest{Name: "slash/test"}, map[string]string{"owner": "user"})
+	_, err := controller.CreateRepository(c)
+	if !strings.ContainsAny(err.Error(), "cannot contain '/' characters") {
```
Comment (tlake) [inline controllers/repository_test.go]: Is there a better way to check that the correct error message is being generated than this string membership?
